# Generated by Django 5.2.6 on 2025-10-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopicprogress',
            name='mastery_level',
            field=models.CharField(choices=[('LEARNING', 'Learning'), ('MASTERED', 'Mastered')], default='LEARNING', max_length=20),
        ),
    ]
