# Generated by Django 5.2.6 on 2025-10-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_usertopicprogress_mastery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='topic_pdfs/'),
        ),
    ]
