# Generated by Django 5.2.6 on 2025-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_topic_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicprogress',
            name='fail_streak',
            field=models.IntegerField(default=0),
        ),
    ]
