# Generated by Django 5.2.6 on 2025-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_usertopicprogress_fail_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicprogress',
            name='high_score_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='pass_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='requires_review',
            field=models.BooleanField(default=False),
        ),
    ]
