# Generated by Django 5.2.6 on 2025-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_usertopicprogress_high_score_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicprogress',
            name='recent_score_gain',
            field=models.FloatField(default=0.0),
        ),
    ]
