# Generated by Django 5.2.6 on 2025-10-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_option_question_topic_delete_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
